---
title: "HITChip Atlas"
author: "Leo Lahti, Sudarshan Shetty et al. `r Sys.Date()`"
bibliography: 
- bibliography.bib
output:
  rmdformats::readthedown:
    self_contained: true
    thumbnails: true
    lightbox: true
    gallery: true
    use_bookdown: false
    highlight: haddock
---
<!--
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{microbiome tutorial - atlas}
  %\usepackage[utf8]{inputenc}
-->


## Intestinal microbiota diversity in 1006 western adults

The data set from [Lahti et al. Nat. Comm. 5:4344, 2014](http://www.nature.com/ncomms/2014/140708/ncomms5344/full/ncomms5344.html) has microbiota profiling of 130 genus-like taxa across 1006 normal western adults from [Data Dryad](http://doi.org/10.5061/dryad.pk75d). Load the data in R:

```{r data2, warning=FALSE, message=FALSE}
# Download the required R packages and then the HITChip Atlas data set
library(microbiome)
data(atlas1006)
```

Estimate ecosystem alpha diversity and related indicators for this data set: 

```{r div-example, warning=FALSE, message=FALSE}
tab <- alpha(atlas1006, index = c("shannon", "invsimpson"))

library(knitr)
kable(head(tab))
```


