#' @title Plot Indicators
#' @description Plot global indicators.
#' This function estimates a number of alpha-diversity metrics using the 
#' \code{\link{estimate_richness}} function,
#' and returns a \code{ggplot} object. 
#' The plot generated by this function will include every sample
#' in \code{physeq}, but they can be further grouped on the horizontal axis
#' through the argument to \code{x}, 
#' and shaded according to the argument to \code{color} (see below).
#' You must use untrimmed, non-normalized count data for meaningful results.
#' @param x \code{\link{phyloseq-class}} object
#' @param y A variable to map to the horizontal axis. The vertical
#'  axis will be mapped to the alpha diversity index/estimate
#'  and have units of total taxa, and/or index value (dimensionless).
#'  This parameter (\code{x}) is a character string indicating a
#'  in the dataset (nsamples(x)).
#' @param index Default is \code{NULL}. In this case
#'  all available alpha-diversity index will be included.
#'  Alternatively, you can specify one or more index
#'  as a character vector. Values must be among those supported:
#'  \code{c("Observed", "Chao1", "ACE", "Shannon", "Simpson", "InvSimpson", "Fisher")}.
#' @param nrow Number of rows for plot faceting.
#' @param scales scales for the plot
#' @param indicate.subjects Indicate subjects by lines. The sample_data(x) must have 'subject' field.
#' @param na.rm Remove samples with missing metadata (NA)
#' @return A \code{\link{ggplot}} plot object summarizing
#'  the richness estimates, and their standard error.
#' @details If subject is among the metadata variables, the matched subjects across groups are indicated by lines.
#' @seealso 
#'  \code{\link{estimate_richness}}
#'  \code{\link{global}}
#'  \code{\link{plot_richness}}
#'  \code{\link[vegan]{estimateR}}
#'  \code{\link[vegan]{diversity}}
#' @export
#' @examples
#'   # Load gut microbiota data on 1006 western adults
#'   # (see help(atlas1006) for references and details)
#'   data(atlas1006)
#'   # Visualize Shannon diversity across bmi groups; remove cases with no bmi info
#'   x <- global(atlas1006)$diversities_shannon
#'   y <- meta(atlas1006)$bmi_group
#'   p <- plot_global(x, variable = y, na.rm = TRUE)
#' @keywords utilities
plot_global <- function(x, y, nrow = 1, scales = "free_y", indicate.subjects = FALSE, na.rm = FALSE){ 

  horiz <- subject <- NULL

  # Coerce to data.frame
  DF <- data.frame(x, y)

  mdf <- gather(DF, "key", "value", dplyr::ends_with(".index"))
  mdf$key <- gsub("\\.index$", "", mdf$key)
  mdf$horiz <- mdf[[variable]]

  if (na.rm) {
    mdf <- dplyr::filter(mdf, !is.na(horiz))
    if (nrow(mdf) == 0) {
      warning(paste("All values in", variable, "are NA. Returning NULL."))
      NULL
    }
  }

  # Make the ggplot  
  theme_set(theme_bw(20))

  if (is.factor(mdf$horiz)) {
  
    p <- ggplot(mdf, aes(x = horiz, y = value))
    
    p <- p + geom_boxplot(na.rm=TRUE)

    if (indicate.subjects) {
      p <- p + geom_point()
      p <- p + geom_line(aes(group = subject))
    }
    
    # Rotate horizontal axis labels, and adjust
    p <- p + theme(axis.text.x=element_text(angle=-90, vjust=0.5, hjust=0))
	
    # Facet wrap using user-options
    p <- p + facet_wrap(~key, nrow = nrow, scales = scales)
	
  } else if (is.vector(mdf$horiz)) {

    if (length(measures) > 1) {
      stop(paste("The horizontal variable", variable, "is numeric. Provide a single diversity measure."))
    }

    p <- plot_regression(value~horiz, mdf)
    p <- p + xlab(variable) 

  }

  # Add y-label and title
  p <- p + ylab('Diversity') 

  p

}
