---
title: "HITChip Atlas"
author: "Leo Lahti, Willem M de Vos et al."
date: "`r Sys.Date()`"
bibliography: 
- bibliography.bib
- references.bib
output: 
  rmarkdown::html_vignette
---
<!--
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{microbiome tutorial - atlas}
  %\usepackage[utf8]{inputenc}
-->


## Intestinal microbiota diversity in 1006 western adults

The data set from [Lahti et al. Nat. Comm. 5:4344,
2014](http://www.nature.com/ncomms/2014/140708/ncomms5344/full/ncomms5344.html)
has microbiota profiling of 130 genus-like taxa across 1006 normal
western adults from [Data Dryad](http://doi.org/10.5061/dryad.pk75d).

Download the data in R:

```{r data2}
# Download the required R packages and then the HITChip Atlas data set
library("microbiome")
data("atlas1006")
pseq <- atlas1006
```


### Diversity 

### Estimating microbial diversity with different diversity measures

```{r div-example, warning=FALSE, message=FALSE, fig.path = "figure/"}
library(phyloseq)
div <- estimate_diversity(pseq, measures = c("Observed", "Shannon", "Simpson"))

library(knitr)
kable(head(div))
```


### Diversity vs. obesity

```{r div-example2, warning=FALSE, message=FALSE, fig.path = "figure/", fig.width=8, fig.height=5}
p <- plot_diversity(pseq, variable = "bmi_group", measures = c("Observed", "Shannon", "Simpson"), det.th = 250)
print(p)
```


### Diversity vs. age

```{r atlas-example3, fig.width=8, fig.height=5, message=FALSE, warning=FALSE, fig.path = "figure/"}
# Pick the subset of RBB-preprocessed samples from time point 0
pseq <- subset_samples(pseq, time == 0 & DNA_extraction_method == "r")

# Visualize
library(sorvi)
p <- sorvi::plot_regression(diversity~age, sample_data(pseq))
print(p)
```


