### Prevalence of taxonomic groups

```{r prevalence, fig.path = "figure/"}
# Load example data
library(microbiome)
pseq <- download_microbiome("peerj32")$physeq
```

List prevalence measure for each group with a given detection threshold:

```{r prevalence2, fig.path = "figure/"}
head(prevalence(pseq, detection.threshold = 10, sort = FALSE))
```

List the taxa that are present over detection threshold in given
fraction of the samples:

```{r prevalence3, fig.path = "figure/"}
prevalent.taxa <- prevalent_taxa(pseq, detection.threshold = 50, prevalence.threshold = 0.2)
```


### Core microbiota

Determine core microbiota with the [blanket
analysis](http://onlinelibrary.wiley.com/doi/10.1111/j.1469-0691.2012.03855.x/abstract)
based on various signal and prevalence thresholds.
 
```{r core-example, message=FALSE, warning=FALSE, fig.path = "figure/"}
core <- core_matrix(pseq, prevalence.intervals = seq(10, 100, 10), detection.thresholds = c(0, 10^(0:4)))
```

### Core 2D line plots

```{r core-example2, fig.width=8, fig.heigth=8, fig.path = "figure/"}
p <- plot_core(pseq, prevalence.intervals = seq(10, 100, 10), detection.thresholds = c(0, 10^(0:4)), plot.type = "lineplot")
```

### Core heatmaps

```{r core-example3, fig.width=8, fig.heigth=13, fig.path = "figure/"}
p <- plot_core(pseq, prevalence.intervals = seq(10, 100, 10), detection.thresholds = c(0, 2^(0:14)), plot.type = "heatmap")
```


```{r core-example4, fig.width=8, fig.heigth=13, fig.path = "figure/"}
p <- core_heatmap(pseq, palette = "spectral")
print(p)
```