### Abundance histograms

Different sample sets have different population distributions in
microbial abundance. It is also important to consider whether to use
absolute or logarithmic abundances.


Visualize population densities for specific taxonomic group:

```{r hist, fig.width=16, fig.heigth=8, fig.path = "figure/"}
library(microbiome)
library(phyloseq)

x <- download_microbiome("atlas1006")
# Pick the subset of RBB-preprocessed samples from time point 0
x <- subset_samples(x, time == 0 & DNA_extraction_method == "r")

# Visualize population densities for specific taxa
plot_density(x, "Prevotella melaninogenica et rel.")
```


Same with log10 abundances:

```{r hist2, fig.width=16, fig.heigth=8, fig.path = "figure/"}
plot_density(x, "Prevotella melaninogenica et rel.", log10 = TRUE)
```


Same with log10 relative abundances:

```{r hist3, fig.width=16, fig.heigth=8, fig.path = "figure/"}
# Convert to relative abundances
x <- transform_sample_counts(x, function (x) {100 * x/sum(x)})

# Visualize
tax <- "Prevotella melaninogenica et rel."
plot_density(x, tax, log10 = TRUE) + ggtitle(paste(tax, "(Rel. Ab. %)"))
```

