#library(devtools)
#load_all()
library(microbiome)
library(knitr)

library(rmarkdown)
rmarkdown::render("vignette.Rmd", output_format = "html_document")
rmarkdown::render("vignette.Rmd", output_format = "pdf_document")
knit("vignette.Rmd")

#system("git add *.md")
#system("git add figure/*")
#system("git add *.Rmd")
#system2("git commit -a -m'vignette update'")
# system("git push origin devel")
