---
title: "Negative binomial"
bibliography: 
- bibliography.bib
- references.bib
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---
<!--
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{microbiome tutorial - comparisons}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}  
-->


## Group-wise comparisons with negative binomial

[Read more on negative binomials](http://www.ats.ucla.edu/stat/r/dae/nbreg.htm)

Load example data:

```{r boxplot-example, warning=FALSE, message=FALSE, fig.width=8, fig.height=5}
# Load libraries
library(microbiome)
library(ggplot2)
library(dplyr)

# Probiotics intervention example data 
data(peerj32) # Source: https://peerj.com/articles/32/
pseq <- peerj32$phyloseq # Rename the example data
```


Visually compare Akkermansia abundance between genders

```{r boxplot2, warning=FALSE, message=FALSE, fig.width=8, fig.height=5, out.width="300px"}
p <- boxplot_abundance(pseq, x = "time", y = "Akkermansia", line = "subject", color = "gender") + scale_y_log10()
print(p)
```

Test statistical significance with negative binomial:

```{r comparisons2b}
library(MASS)

# Analyse specific taxa
tax <- "Akkermansia"

# Pick the signal (abundance) for this tax
sample_data(pseq)$signal <- get_sample(pseq, tax)

# Negative binomial test with group and gender included
res <- glm.nb(signal ~ group + gender, data = meta(pseq))

# Show the results
print(coef(summary(res)))
```



```{r cleanup, echo=FALSE, warning=FALSE, message=FALSE}
    # Must do to clean up some space
    pkgs0 <- c("ade4",
      	       "compositions",
    	       "MASS",
    	       "moments",
    	       "scales",
    	       "tgp",
    	       "WGCNA",
    	       "diptest",
    	       "FD",
    	       "gcookbook",
    	       "GGally",
    	       "ggnet",
    	       "Hmisc",
    	       "hrbrthemes",
    	       "igraph",
    	       "intergraph",
    	       "limma",
    	       "lme4",
    	       "netresponse",
    	       "network",
    	       "RColorBrewer",
    	       "sna",
    	       "SpiecEasi",
    	       "tidyverse",
    	       "viridis")
    for (pkg in pkgs0) {
        print(pkg)
        try(a <- unloadNamespace(pkg))
    }
```




