---
title: "Networks"
author: "Leo Lahti"
date: "`r Sys.Date()`"
bibliography: 
- bibliography.bib
- references.bib
output: 
  rmarkdown::html_vignette
---
<!--
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{microbiome tutorial - networks}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}  
-->


## Networks

Load example data:

```{r networks1, message=FALSE, warning=FALSE}
library(microbiome)
data("dietswap")
pseq <- dietswap
```

For more network examples, see
[phyloseq tutorial](http://joey711.github.io/phyloseq/plot_network-examples)

```{r networks2, warning=FALSE, message=FALSE}
ig <- make_network(pseq, max.dist = 0.2)
p <- plot_network(ig, pseq, color = "nationality", shape = "group",
		 line_weight = 0.4, label = "sample")
print(p)		 
```

Another example:

```{r networks3, warning=FALSE, message=FALSE}
p <- plot_net(pseq, maxdist = 0.2, point_label = "group")
print(p)		 
```

### Network reconstruction for compositional data

Also the SparCC implementation is available via the [SpiecEasi
package](https://github.com/zdk123/SpiecEasi). The execution is slow.


```{r networks4, warning=FALSE, message=FALSE, fig.width=10, fig.height=10}
library(SpiecEasi) #install_github("zdk123/SpiecEasi")
library(phyloseq)
otu <- t(get_sample(pseq))

# SPIEC-EASI network reconstruction
# In practice, use more repetitions
net <- spiec.easi(otu, method='mb', lambda.min.ratio=1e-2, 
                  nlambda=20, icov.select.params=list(rep.num=20))

## Create graph object
n <- net$refit
colnames(n) <- rownames(n) <- colnames(otu)

# Network format
library(network)
netw <- network(as.matrix(n), directed = FALSE)

# igraph format
library(igraph)
ig <- graph.adjacency(n, mode='undirected', add.rownames = TRUE)

## set size of vertex to log2 mean abundance 
vsize <- log2(apply(otu, 2, mean))

# Network layout
coord <- layout.fruchterman.reingold(ig)

# Visualize the network
print(plot(ig, layout = coord, vertex.size = vsize, vertex.label = names(vsize)))

# Check degree distribution
#dd <- degree.distribution(ig)
#plot(0:(length(dd)-1), dd, ylim=c(0,.35), type='b', 
#      ylab="Frequency", xlab="Degree", main="Degree Distributions")
```


Visualize the network with [ggnet2](https://briatte.github.io/ggnet):

```{r networks5, warning=FALSE, message=FALSE, fig.width=10, fig.height=7}
library(GGally)
library(ggnet)
library(network)
library(sna)
library(ggplot2)
library(intergraph) # ggnet2 works also with igraph with this

phyla <- map_levels(colnames(otu), from = "Genus", to = "Phylum",
           tax_table(pseq))
netw %v% "Phylum" <- phyla
p <- ggnet2(netw, color = "Phylum", label = TRUE, label.size = 2)
print(p)
```
