### Data projections

Project high-dimensional data on two-dimensional plane by various methods including PCA, MDS, Sammons mapping etc. (for visualization purposes; see help(project.data) for details):  

```{r visu-example, message=FALSE, message=FALSE, fig.height=8, fig.width=8}
library(microbiome, quietly = TRUE)
data.directory <- system.file("extdata", package = "microbiome")
genus.matrix.log10.simulated <- read.profiling(level = "L2", method = "frpa", 
			              data.dir = data.directory, log10 = TRUE)

# Note: transpose the data matrix into samples x features
proj <- project.data(t(genus.matrix.log10.simulated), type = "MDS.nonmetric")

# Plot the projection
library(ggplot2); 
theme_set(theme_bw(15))
ggplot(aes(x = Comp.1, y = Comp.2), data = proj) + geom_point()
```

Plot the projection with sample names:

```{r visu-example2, message=FALSE, message=FALSE, fig.height=8, fig.width=8}
ggplot(aes(x = Comp.1, y = Comp.2, label = rownames(proj)), data = proj) + geom_text()
```
