### RDA analysis and visualization. 

Load the package and example data:

```{r rda, warning=FALSE, message=FALSE, fig.path = "figure/"}
library(microbiome, quietly = TRUE)
data(peerj32)  # From https://peerj.com/articles/32/

# Microbiota profiling data (44 samples x 130 bacteria)
l2 <- peerj32$microbes  

# Sample annotations
annot <- peerj32$meta
```

### Standard RDA 

Run standard RDA for microbiota profiles versus timepoint

```{r rda2, warning=FALSE, message=FALSE, fig.width=8, fig.height=8, fig.path = "figure/"}
library(vegan)
rdatest<-rda(l2~annot$time) # Run RDA
permutest(rdatest) # RDA Significance test
```

### Controlling for confounding variables

```{r rda3, warning=FALSE, message=FALSE, fig.width=8, fig.height=8, fig.path = "figure/"}
rdatest<-rda(l2~annot$time + Condition(annot$subject)) 
permutest(rdatest) # RDA significance test

# Including even more confounders (not run):
# rdatest<-rda(l2~annot$time + Condition(annot$subject + annot$sample))
```

### RDA visualization

Visualizing the standard RDA output:

```{r rda4, warning=FALSE, message=FALSE, fig.width=8, fig.height=8, fig.path = "figure/"}
plot(rdatest, choices=c(1,2), type="points", pch=15, scaling=3, cex=0.7, col=annot$time)
points(rdatest, choices=c(1,2), pch=15, scaling=3, cex=0.7, col=annot$time)
pl <- ordihull(rdatest, annot$time, scaling = 3, label = TRUE)
title("RDA with control for subject effect")
```

### Bagged RDA

Calculate Bagged RDA and visualize the results:

```{r rda5, warning=FALSE, message=FALSE, fig.width=8, fig.height=8}
library(microbiome)
# Modify the group vector into a facor as required by Bagged RDA
y <- factor(annot$time); names(y) <- rownames(annot)

# Bagged RDA
Bag.res <- Bagged.RDA.Feature.Selection(t(l2), y, sig.thresh=0.05, nboot=100)

# Visualize
PlotBaggedRDA(Bag.res, y)
```

