---
title: "Regression"
bibliography: 
- bibliography.bib
- references.bib
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---
<!--
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteIndexEntry{microbiome tutorial - regression}
  %\usepackage[utf8]{inputenc}
  %\VignetteEncoding{UTF-8}  
-->


## Regression plots

Load example data

```{r heterogeneity-example2, message=FALSE}
library(microbiome)
data(atlas1006)
pseq <- atlas1006
```

Regression curve with smoothed error bars based on
the [Visually-Weighted Regression](http://www.fight-entropy.com/2012/07/visually-weighted-regression.html) by Solomon M. Hsiang. The sorvi implementation extends [Felix Schonbrodt's original code](http://www.nicebread.de/visually-weighted-watercolor-plots-new-variants-please-vote/). See also [potential analysis](Potential.html).

```{r variability-regression, message=FALSE, eval=TRUE, fig.width=10, fig.height=5, warning=FALSE, dev="CairoPNG"}
p <- plot_regression(diversity ~ age, meta(pseq))
print(p)
```

```{r cleanup, echo=FALSE, warning=FALSE, message=FALSE}
    # Must do to clean up some space
    pkgs0 <- c("ade4",
      	       "compositions",
    	       "MASS",
    	       "moments",
    	       "scales",
    	       "tgp",
    	       "WGCNA",
    	       "diptest",
    	       "FD",
    	       "gcookbook",
    	       "GGally",
    	       "ggnet",
    	       "Hmisc",
    	       "hrbrthemes",
    	       "igraph",
    	       "intergraph",
    	       "limma",
    	       "lme4",
    	       "netresponse",
    	       "network",
    	       "RColorBrewer",
    	       "sna",
    	       "SpiecEasi",
    	       "tidyverse",
    	       "viridis")
    for (pkg in pkgs0) {
        print(pkg)
        try(a <- unloadNamespace(pkg))
    }
```



