### ROC analysis

A basic example of ROC/AUC analysis.


### Load example data

```{r roc-example, warning=FALSE, fig.path = "figure/"}
library(microbiome)
pseq <- download_microbiome("dietswap")

# Pick two groups of samples
# African, DI group, time points 1 and 2
# See the original publication for details: 
# references provided in help(dietswap)
pseq1 <- subset_samples(pseq, nationality == "AFR" & 
		     timepoint.within.group == 1 & 
		     group == "DI")
pseq2 <- subset_samples(pseq, nationality == "AFR" & 
		     timepoint.within.group == 2 & 
		     group == "DI")

# Pick OTU matrix
otu <- otu_table(pseq)@.Data

# Pick sample metadata
meta <- sample_data(pseq)

# Define two sample groups for demonstration purpose
g1 <- sample_names(pseq1)
g2 <- sample_names(pseq2)

# Compare the two groups with Wilcoxon test
pvalues <- c()
for (tax in rownames(otu)) {
  pvalues[[tax]] <- wilcox.test(otu[tax, g1], otu[tax, g2])$p.value
}

# Assume there are some known true positives 
# Here for instance Bacteroidetes
bacteroidetes <- levelmap("Bacteroidetes", from = "L1", to = "L2", GetPhylogeny("HITChip", "filtered"))$Bacteroidetes
```


### Overall ROC analysis 

This gives the cumulative TPR and FPR along the ordered list

```{r roc-example, warning=FALSE, fig.path = "figure/"}
# Order the taxa based on the p-values
ordered.results <- names(sort(pvalues))

# Define true positive taxa to be tested for enrichment
true.positives <- bacteroidetes

# ROC analysis
res <- roc(ordered.results, true.positives)
```


### Calculate ROC/AUC value

```{r roc-example, warning=FALSE, fig.path = "figure/"}
auc <- roc.auc(ordered.results, true.positives)
print(auc)
```


### Plot ROC curve

```{r roc-example, warning=FALSE, fig.path = "figure/"}
roc.plot(ordered.results, true.positives, line = TRUE)
```
