### Taxonomic network reconstruction 

```{r networks1, message=FALSE, warning=FALSE}
pseq <- transform(atlas1006, "compositional")

# Keep only the prevalent taxa 
pseq <- core(pseq, detection = 0.2/100, prevalence = 80/100)
pseq <- subset_samples(pseq, DNA_extraction_method == "r")
```

The compositionality bias can be fixed with SpiecEasi or SparCC; the
implementations are available via the [SpiecEasi
package](https://github.com/zdk123/SpiecEasi). Note that the execution
is slow.


```{r spieceasi, warning=FALSE, message=FALSE, fig.width=10, fig.height=10, eval=TRUE}
library(SpiecEasi) #install_github("zdk123/SpiecEasi")
library(phyloseq)

# Pick the OTU table
otu <- abundances(pseq)
net <- spiec.easi(t(otu), method='mb', icov.select.params=list(rep.num=100))

## Create graph object
n <- net$refit
colnames(n) <- rownames(n) <- rownames(otu)

# Network Format
library(network)
netw <- network(as.matrix(n), directed = FALSE)
```


Visualize the network with [ggnet2](https://briatte.github.io/ggnet):

```{r networks5, warning=FALSE, message=FALSE, fig.width=12, fig.height=7}
library(GGally)
library(ggnet)
library(network)
library(sna)
library(ggplot2)
library(intergraph) # ggnet2 works also with igraph with this

phyla <- map_levels(rownames(otu),
           from = "Genus", to = "Phylum",
           tax_table(pseq))

netw %v% "Phylum" <- phyla
p <- ggnet2(netw, color = "Phylum", label = TRUE, label.size = 2)
print(p)
```



See the [phyloseq tutorial](http://joey711.github.io/phyloseq/plot_network-examples) for
additional network visualization tools.

