%\VignetteIndexEntry{microbiome}
%The above line is needed to remove a warning in R CMD check
\documentclass[a4paper]{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath,amsthm,amsfonts}
\usepackage{graphicx}
%\usepackage[T1]{fontenc}
%\usepackage[latin1]{inputenc}
%\usepackage[authoryear,round]{natbib}
\usepackage[numbers]{natbib}
\usepackage{hyperref}
\usepackage{Sweave}
\usepackage{float}

\setlength{\textwidth}{450pt}
\setlength{\oddsidemargin}{20pt}
\setlength{\evensidemargin}{20pt}
%\setlength{\marginparwidth}{55pt}

\setlength{\parindent}{0mm}
\setlength{\parskip}{2mm}
\setlength{\topmargin}{5pt}
\addtolength{\textheight}{50pt}
%\textwidth=6.2in
%\textheight=8.5in
%\oddsidemargin=.1in
%\evensidemargin=.1in
%\headheight=-.3in

\newcommand{\Rfunction}[1]{{\texttt{#1}}}
\newcommand{\Robject}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}

\title{microbiome\\R package and protocols}
\author{Leo Lahti\footnote{Wageningen University, Netherlands}, Jarkko
Saloj{\"a}rvi\footnote{University of Helsinki, Finland}}

%\hyphenation{}

\begin{document}

\maketitle

The microbiome package includes standard
R routines for preprocessing, analysis and visualization of microbiomics
profiling data. The package is jointly developed by researchers from
the Molecular Ecology group, Laboratory of Microbiology, Wageningen
University, Netherlands, and Gut Group, Department of Veterinary
Bioscience, University of Helsinki, Finland. 

% Many people have contributed to the project, 
% including Leo Lahti, Jarkko Salojärvi, Douwe Molenaar, Janne Nikkilä, Jonna Jalanka-Tuovinen, 
% Susana Fuentes, Sebastian Tims, Hauke Smidt, and Willem M de Vos.

The current version is in beta. The features and documentation are unstable and under development. For 
further information, check the website: http://microbiome.github.com or contact the admins 
through microbiome-admin@googlegroups.com

For installation instructions and other documentation, see
https://github.com/microbiome/microbiome/wiki/

To citation information, check in R: citation("microbiome")


\section{Version information}

<<details>>=
sessionInfo()
@


%\bibliographystyle[numbers]{natbib} 
%\begin{thebibliography}{1}
%\bibliographystyle{abbrv}
%\bibliography{my.bib}

\end{document}
