#' @importFrom dplyr arrange
#' @importFrom dplyr do
#' @importFrom dplyr filter
#' @importFrom dplyr group_by
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr summarise
#' @importFrom dplyr n
#' @importFrom dplyr mutate
#' @importFrom dplyr %>%
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 aes_string
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 coord_cartesian
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_rect
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 facet_grid
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_density
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_jitter
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_linerange
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 geom_path
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_polygon
#' @importFrom ggplot2 geom_smooth
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 geom_violin
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 labs
#' @importFrom ggplot2 position_jitter
#' @importFrom ggplot2 scale_alpha_continuous
#' @importFrom ggplot2 scale_colour_gradient2
#' @importFrom ggplot2 scale_x_log10
#' @importFrom ggplot2 scale_y_log10
#' @importFrom ggplot2 scale_fill_gradientn
#' @importFrom ggplot2 scale_fill_gradient
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 scale_size_manual
#' @importFrom ggplot2 scale_size
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 stat_density2d
#' @importFrom ggplot2 theme_set
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom phyloseq distance
#' @importFrom phyloseq estimate_richness
#' @importFrom phyloseq get_taxa
#' @importFrom phyloseq get_variable
#' @importFrom phyloseq merge_phyloseq
#' @importFrom phyloseq merge_taxa
#' @importFrom phyloseq nsamples
#' @importFrom phyloseq ntaxa
#' @importFrom phyloseq ordinate
#' @importFrom phyloseq otu_table
#' @importFrom phyloseq otu_table<-
#' @importFrom phyloseq phyloseq
#' @importFrom phyloseq psmelt
#' @importFrom phyloseq prune_samples
#' @importFrom phyloseq prune_taxa
#' @importFrom phyloseq rank_names
#' @importFrom phyloseq sample_data
#' @importFrom phyloseq sample_sums
#' @importFrom phyloseq sample_data<-
#' @importFrom phyloseq sample_names
#' @importFrom phyloseq taxa_are_rows<-
#' @importFrom phyloseq taxa_are_rows
#' @importFrom phyloseq taxa_names
#' @importFrom phyloseq taxa_sums
#' @importFrom phyloseq taxa_names<-
#' @importFrom phyloseq tax_glom
#' @importFrom phyloseq tax_table
#' @importFrom phyloseq tax_table<-
#' @importFrom phyloseq import_biom
#' @importFrom phyloseq parse_taxonomy_default
#' @importFrom Rtsne Rtsne
#' @importFrom reshape2 melt
#' @importFrom scales percent
#' @importFrom stats aggregate
#' @importFrom stats as.dist
#' @importFrom stats coef
#' @importFrom stats cor
#' @importFrom stats cor.test
#' @importFrom stats density
#' @importFrom stats dist
#' @importFrom stats dnorm
#' @importFrom stats hclust
#' @importFrom stats kernel
#' @importFrom stats lm
#' @importFrom stats loess
#' @importFrom stats loess.control
#' @importFrom stats median
#' @importFrom stats na.fail
#' @importFrom stats na.omit
#' @importFrom stats p.adjust
#' @importFrom stats pnorm
#' @importFrom stats predict
#' @importFrom stats princomp
#' @importFrom stats quantile
#' @importFrom stats rnorm
#' @importFrom stats sd
#' @importFrom stats time
#' @importFrom stats frequency
#' @importFrom tibble data_frame
#' @importFrom tidyr separate
#' @importFrom utils capture.output
#' @importFrom utils flush.console
#' @importFrom utils head
#' @importFrom utils read.csv
#' @importFrom utils read.table
#' @importFrom utils tail
#' @importFrom utils write.csv
#' @importFrom vegan decostand
#' @importFrom vegan fisher.alpha
#' @importFrom vegan metaMDS
#' @importFrom vegan scores
#' @importFrom vegan vegdist
#' @importFrom vegan wascores
.onAttach <- function(lib, pkg) {
    packageStartupMessage("\nmicrobiome R package (microbiome.github.com)
    \n\n\n Copyright (C) 2011-2022 Leo Lahti, 
    Sudarshan Shetty et al. <microbiome.github.io>\n")
}

# As far as I understand the problem, running into this error / limit is _not_
# the fault of the user.  Instead, I'd argue that it is the responsibility of
# package developers to make sure to unregister any registered DLLs of theirs
# when the package is unloaded.  A developer can do this by adding the following
# to their package: .onUnload <- function(libpath) {
# library.dynam.unload(utils::packageName(), libpath) }
