#' @importFrom dplyr arrange
#' @importFrom dplyr funs
#' @importFrom dplyr summarize_each
#' @importFrom dplyr summarise
#' @importFrom dplyr n
#' @importFrom dplyr mutate
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 aes_string
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 facet_wrap
#' @importFrom ggplot2 geom_bar
#' @importFrom ggplot2 geom_boxplot
#' @importFrom ggplot2 geom_density
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 geom_line
#' @importFrom ggplot2 geom_linerange
#' @importFrom ggplot2 geom_hline
#' @importFrom ggplot2 geom_vline
#' @importFrom ggplot2 geom_point
#' @importFrom ggplot2 geom_text
#' @importFrom ggplot2 geom_segment
#' @importFrom ggplot2 geom_tile
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 ggtitle
#' @importFrom ggplot2 guides
#' @importFrom ggplot2 guide_legend
#' @importFrom ggplot2 scale_x_log10
#' @importFrom ggplot2 scale_y_log10
#' @importFrom ggplot2 scale_fill_gradientn
#' @importFrom ggplot2 scale_fill_gradient
#' @importFrom ggplot2 scale_x_discrete
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_discrete
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 scale_size_manual
#' @importFrom ggplot2 scale_color_manual
#' @importFrom ggplot2 stat_density2d
#' @importFrom ggplot2 theme_set
#' @importFrom ggplot2 theme_bw
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 xlab
#' @importFrom ggplot2 ylab
#' @importFrom MASS bandwidth.nrd
#' @importFrom phyloseq get_taxa
#' @importFrom phyloseq otu_table
#' @importFrom phyloseq psmelt
#' @importFrom phyloseq sample_data
#' @importFrom phyloseq sample_names
#' @importFrom phyloseq prune_taxa
#' @importFrom phyloseq taxa_names
#' @importFrom phyloseq taxa_are_rows
#' @importFrom phyloseq tax_table
#' @importFrom phyloseq transform_sample_counts
#' @importFrom RColorBrewer brewer.pal
#' @importFrom RPA summarize_probedata
.onAttach <- function(lib, pkg) {
    packageStartupMessage("\nmicrobiome R package (microbiome.github.com)
          \n\n\n Copyright (C) 2011-2016
          Leo Lahti and Jarkko Salojarvi \n\n        
          <microbiome-admin@googlegroups.com>\n")
} 
