#' @title Plot Diversity
#' @description Plot alpha diversity.
#' This function estimates a number of alpha-diversity metrics using the 
#' \code{\link{estimate_richness}} function,
#' and returns a \code{ggplot} object. 
#' The plot generated by this function will include every sample
#' in \code{physeq}, but they can be further grouped on the horizontal axis
#' through the argument to \code{x}, 
#' and shaded according to the argument to \code{color} (see below).
#' You must use untrimmed, non-normalized count data for meaningful results.
#' @param x \code{\link{phyloseq-class}} object
#' @param variable A variable to map to the horizontal axis. The vertical
#'  axis will be mapped to the alpha diversity index/estimate
#'  and have units of total taxa, and/or index value (dimensionless).
#'  This parameter (\code{x}) is a character string indicating a
#'  in the dataset (nsamples(x)).
#' @param measures Default is \code{NULL}. In this case
#'  all available alpha-diversity measures will be included.
#'  Alternatively, you can specify one or more measures
#'  as a character vector. Values must be among those supported:
#'  \code{c("Observed", "Chao1", "ACE", "Shannon", "Simpson", "InvSimpson", "Fisher")}.
#' @param nrow Number of rows for plot faceting.
#' @param scales scales for the plot
#' @param detection Detection threshold for the diversity measure 'Observed' 
#'               (ie. species richness). See \code{\link{diversity}}
#' @param indicate.subjects Indicate subjects by lines. The sample_data(x) must have 'subject' field.
#' @param na.rm Remove samples with missing metadata (NA)
#' @return A \code{\link{ggplot}} plot object summarizing
#'  the richness estimates, and their standard error.
#' @details If subject is among the metadata variables, the matched subjects across groups are indicated by lines.
#' @seealso 
#'  \code{\link{estimate_richness}}
#'  \code{\link{diversity}}
#'  \code{\link{plot_richness}}
#'  \code{\link[vegan]{estimateR}}
#'  \code{\link[vegan]{diversity}}
#' @export
#' @examples p <- plot_diversity(x, variable = "bmi_group", "Shannon")
#' @keywords utilities
plot_diversity <- function(x, variable = "group", measures = "Shannon", nrow = 1, scales = "free_y", detection = 0, indicate.subjects = FALSE, na.rm = FALSE){ 

  horiz <- subject <- NULL

  # Calculate alpha-diversity measures
  erDF <- diversity(x, split = TRUE, measures = measures, detection = detection)

  # Measures may have been renamed in `erDF`. Replace it with the name from erDF
  measures <- colnames(erDF)

  # Define "measure" variables and s.e. labels, for melting.
  ses <- colnames(erDF)[grep("^se\\.", colnames(erDF))]

  # Remove any S.E. from `measures`
  measures <- measures[!measures %in% ses]

  # Coerce to data.frame
  if( !is.null(sample_data(x, errorIfNULL=FALSE)) ){
    # Include the sample data, if it is there.
    DF <- data.frame(erDF, sample_data(x))
  } else {
    # If no sample data, leave it out.
    DF <- data.frame(erDF)
  }

  value <- NULL
  for (nam in measures) {
   names(DF) <- gsub(nam, paste(nam, ".diversity", sep = ""), names(DF))
  }

  mdf <- gather(DF, "key", "value", dplyr::ends_with(".diversity"))
  mdf$key <- gsub("\\.diversity$", "", mdf$key)
  mdf$horiz <- mdf[[variable]]

  if (na.rm) {
    mdf <- dplyr::filter(mdf, !is.na(horiz))
    if (nrow(mdf) == 0) {
      warning(paste("All values in", variable, "are NA. Returning NULL."))
      NULL
    }
  }

  # Make the ggplot  
  theme_set(theme_bw(20))

  if (is.factor(mdf$horiz)) {
  
    p <- ggplot(mdf, aes(x = horiz, y = value))
    
    p <- p + geom_boxplot(na.rm=TRUE)

    if (indicate.subjects) {
      p <- p + geom_point()
      p <- p + geom_line(aes(group = subject))
    }
    
    # Rotate horizontal axis labels, and adjust
    p <- p + theme(axis.text.x=element_text(angle=-90, vjust=0.5, hjust=0))
	
    # Facet wrap using user-options
    p <- p + facet_wrap(~key, nrow = nrow, scales = scales)
	
  } else if (is.vector(mdf$horiz)) {

    if (length(measures) > 1) {
      stop(paste("The horizontal variable", variable, "is numeric. Provide a single diversity measure."))
    }

    p <- plot_regression(value~horiz, mdf)
    p <- p + xlab(variable) 

  }

  # Add y-label and title
  p <- p + ylab('Diversity') 

  p

}
